const KEY='retromax-games-v2-private';
const APP_VERSION='0.0.12';
const DEFAULT_ACCENT='#f7cf46';
const CONSOLE_CATALOG={
  Sony:['PlayStation 1','PlayStation 2','PlayStation 3','PlayStation 4','PlayStation 5','PSP','PS Vita'],
  Nintendo:['NES','Super Nintendo','Nintendo 64','GameCube','Wii','Wii U','Switch','Nintendo Switch 2','Game Boy','Game Boy Color','Game Boy Advance','Nintendo DS','Nintendo 3DS'],
  Sega:['Master System','Mega Drive','Saturn','Dreamcast','Game Gear'],
  Microsoft:['Xbox','Xbox 360','Xbox One','Xbox Series']
};
const PLATFORM_THEMES=[
  {key:'ps5',match:/playstation 5|\bps5\b/,color:'#f1f5ff',mark:'PS5',logo:'playstation5',shape:'wordmark',mode:'image'},
  {key:'ps4',match:/playstation 4|\bps4\b/,color:'#147bd1',mark:'PS4',logo:'playstation4',shape:'wordmark',mode:'image'},
  {key:'ps3',match:/playstation 3|\bps3\b/,color:'#aeb8c7',mark:'PS3',logo:'playstation3',shape:'wordmark',mode:'image'},
  {key:'ps2',match:/playstation 2|\bps2\b/,color:'#6574ff',mark:'PS2',logo:'playstation2',shape:'wordmark',mode:'image'},
  {key:'psvita',match:/ps vita|playstation vita/,color:'#20a9e0',mark:'VITA',logo:'psvita',shape:'handheld-wordmark',mode:'image'},
  {key:'psp',match:/\bpsp\b|playstation portable/,color:'#9aa5b8',mark:'PSP',logo:'psp',shape:'handheld-wordmark',mode:'image'},
  {key:'n64',match:/nintendo 64|\bn64\b/,color:'#069330',mark:'N64',logo:'nintendo64',mode:'image'},
  {key:'snes',match:/super nintendo|super nes|\bsnes\b|super famicom/,color:'#6eb92b',mark:'SNES',logo:'super-nintendo',mode:'image'},
  {key:'nes',match:/nintendo entertainment system|\bnes\b/,color:'#e60012',mark:'NES',logo:'nintendo-nes',shape:'legacy-wordmark',mode:'image'},
  {key:'gamecube',match:/gamecube/,color:'#7357d6',mark:'GC',logo:'gamecube'},
  {key:'switch2',match:/nintendo switch 2|switch 2/,color:'#e60012',mark:'NS2',logo:'nintendo-switch-2',shape:'legacy-wordmark',mode:'image'},
  {key:'switch',match:/switch/,color:'#e60012',mark:'NS',logo:'nintendo-switch'},
  {key:'wiiu',match:/wii u|wiiu/,color:'#00a7e0',mark:'WiiU',logo:'nintendo-wiiu',shape:'legacy-wordmark',mode:'image'},
  {key:'wii',match:/\bwii\b/,color:'#00a7e0',mark:'Wii',logo:'nintendo-wii'},
  {key:'gameboyadvance',match:/game boy advance|\bgba\b/,color:'#6545a5',mark:'GBA',logo:'game-boy-advance',shape:'legacy-wordmark',mode:'image'},
  {key:'gameboycolor',match:/game boy color|\bgbc\b/,color:'#9b4d96',mark:'GBC',logo:'game-boy-color',shape:'legacy-wordmark',mode:'image'},
  {key:'gameboy',match:/game boy/,color:'#2f328c',mark:'GB',logo:'game-boy',shape:'legacy-wordmark',mode:'image'},
  {key:'3ds',match:/nintendo 3ds|\b3ds\b/,color:'#e60012',mark:'3DS',logo:'nintendo-3ds',shape:'legacy-wordmark',mode:'image'},
  {key:'ds',match:/nintendo ds|\bds\b/,color:'#aeb8c7',mark:'DS',logo:'nintendo-ds',shape:'legacy-wordmark',mode:'image'},
  {key:'mastersystem',match:/master system/,color:'#e4312b',mark:'MS',logo:'master-system',shape:'legacy-wordmark',mode:'image'},
  {key:'megadrive',match:/mega drive|genesis/,color:'#ff5a2a',mark:'MD',logo:'mega-drive',shape:'legacy-wordmark',mode:'image'},
  {key:'saturn',match:/saturn/,color:'#5b7fb8',mark:'SAT',logo:'sega-saturn',mode:'image'},
  {key:'dreamcast',match:/dreamcast/,color:'#f36f21',mark:'DC',logo:'dreamcast'},
  {key:'xboxseries',match:/xbox series/,color:'#107c10',mark:'XS',logo:'xbox-series',shape:'legacy-wordmark',mode:'image'},
  {key:'xboxone',match:/xbox one/,color:'#107c10',mark:'X1',logo:'xbox-one',shape:'legacy-wordmark',mode:'image'},
  {key:'xbox360',match:/xbox 360/,color:'#6abf4b',mark:'360',logo:'xbox-360',shape:'legacy-wordmark',mode:'image'},
  {key:'xbox',match:/xbox/,color:'#52b043',mark:'XB',logo:'xbox-original',shape:'legacy-wordmark',mode:'image'},
  {key:'playstation',match:/playstation(?: 1)?|\bps1\b|sony/,color:'#1675d1',mark:'PS',logo:'playstation-classic',mode:'image'},
  {key:'nintendo',match:/nintendo|\bnes\b|game boy|\bwii\b|\b3ds\b|\bds\b/,color:'#e60012',mark:'N',logo:'nintendo-mark',mode:'image'},
  {key:'sega',match:/sega|master system|mega drive|saturn|game gear/,color:'#0089cf',mark:'SEGA',logo:'sega'},
  {key:'microsoft',match:/microsoft/,color:'#52b043',mark:'MS',logo:'xbox'}
];
let games=load();
const $=s=>document.querySelector(s);
const els={stats:$('#stats'),search:$('#search'),mf:$('#manufacturerFilter'),cf:$('#consoleFilter'),sf:$('#statusFilter'),cards:$('#manufacturerCards'),list:$('#gameList'),empty:$('#emptyState'),result:$('#resultTitle'),dialog:$('#gameDialog'),form:$('#gameForm'),welcome:$('#emptyWelcome'),privacy:$('#privacyBanner'),file:$('#importFile')};
$('#appVersion').textContent=`v${APP_VERSION}`;
function load(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):[]}catch{return []}}
function save(){localStorage.setItem(KEY,JSON.stringify(games))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uniq(xs){return [...new Set(xs.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'))}
function platformTheme(consoleName='',manufacturer=''){const haystack=`${consoleName} ${manufacturer}`.toLowerCase();return PLATFORM_THEMES.find(theme=>theme.match.test(haystack))||{key:'other',color:DEFAULT_ACCENT,mark:'•'}}
function platformStyle(theme){return `--platform-accent:${theme.color};--platform-soft:${theme.color}24${theme.logo?`;--platform-logo:url(assets/platforms/${theme.logo}.svg)`:''}`}
function platformMark(theme,label){const mode=theme.mode||'mask',shape=theme.shape||'emblem',image=theme.logo&&mode==='image'?`<img class="platform-logo-image" src="assets/platforms/${theme.logo}.svg?v=${APP_VERSION}" alt="" loading="lazy">`:'';return `<span class="platform-mark" data-platform-logo="${theme.key}" data-logo-mode="${mode}" data-logo-shape="${shape}" data-has-logo="${theme.logo?'true':'false'}" role="img" aria-label="${esc(label)}">${image}<span class="platform-fallback">${esc(theme.mark)}</span></span>`}
function applyActiveTheme(){const theme=els.cf.value?platformTheme(els.cf.value):els.mf.value?platformTheme('',els.mf.value):null;document.documentElement.style.setProperty('--accent',theme?.color||DEFAULT_ACCENT);document.documentElement.style.setProperty('--accent-soft',theme?`${theme.color}24`:'#f7cf4624');document.body.dataset.activePlatform=theme?.key||'all'}
function populateFilters(manufacturer=els.mf.value,consoleName=els.cf.value){const m=uniq(games.map(g=>g.manufacturer));els.mf.innerHTML='<option value="">Tous les constructeurs</option>'+m.map(x=>`<option>${esc(x)}</option>`).join('');els.mf.value=m.includes(manufacturer)?manufacturer:'';const c=uniq(games.filter(g=>!els.mf.value||g.manufacturer===els.mf.value).map(g=>g.console));els.cf.innerHTML='<option value="">Toutes les consoles</option>'+c.map(x=>`<option>${esc(x)}</option>`).join('');els.cf.value=c.includes(consoleName)?consoleName:'';const fm=$('#manufacturer'),fc=$('#console'),allConsoles=uniq(games.map(g=>g.console));fm.innerHTML=m.length?m.map(x=>`<option>${esc(x)}</option>`).join(''):'<option>Sony</option><option>Nintendo</option><option>Sega</option><option>Microsoft</option>';fc.innerHTML=allConsoles.length?allConsoles.map(x=>`<option>${esc(x)}</option>`).join(''):'<option>PlayStation 1</option>'}
function visible(){const q=els.search.value.trim().toLowerCase(),mf=els.mf.value,cf=els.cf.value,sf=els.sf.value;return games.filter(g=>(!q||[g.title,g.console,g.manufacturer,g.region,g.format,...(g.tags||[])].join(' ').toLowerCase().includes(q))&&(!mf||g.manufacturer===mf)&&(!cf||g.console===cf)&&(!sf||g.status===sf)).sort((a,b)=>(a.console||'').localeCompare(b.console||'','fr')||(a.title||'').localeCompare(b.title||'','fr'))}
function render(){applyActiveTheme();const has=games.length>0;els.welcome.classList.toggle('hidden',has);els.privacy.classList.toggle('hidden',!has);const owned=games.filter(g=>g.status==='Acquis'),wanted=games.filter(g=>g.status==='Recherché');els.stats.innerHTML=`<div class="stat"><strong>${owned.reduce((n,g)=>n+(g.quantity||1),0)}</strong><span>exemplaires acquis</span></div><div class="stat"><strong>${uniq(games.map(g=>g.console)).length}</strong><span>consoles</span></div><div class="stat"><strong>${wanted.length}</strong><span>recherchés</span></div>`;const makers=uniq(games.map(g=>g.manufacturer));els.cards.innerHTML=makers.map(m=>{const n=games.filter(g=>g.manufacturer===m&&g.status==='Acquis').reduce((s,g)=>s+(g.quantity||1),0),theme=platformTheme('',m);return `<button class="maker-card ${els.mf.value===m?'active':''}" data-maker="${esc(m)}" data-platform="${theme.key}" style="${platformStyle(theme)}">${platformMark(theme,m)}<span class="maker-copy"><strong>${esc(m)}</strong><span>${n} exemplaires · ${uniq(games.filter(g=>g.manufacturer===m).map(g=>g.console)).length} consoles</span></span></button>`}).join('');const v=visible();const label=[els.mf.value,els.cf.value,els.sf.value].filter(Boolean).join(' · ')||'Toute la collection';els.result.textContent=`${label} (${v.length})`;els.list.innerHTML=v.map(g=>{const theme=platformTheme(g.console,g.manufacturer);return `<article class="game-card" data-id="${esc(g.id)}" data-platform="${theme.key}" style="${platformStyle(theme)}">${platformMark(theme,g.console)}<div class="game-copy"><h3>${esc(g.title)}</h3><div class="meta"><span class="pill console-pill">${esc(g.console)}</span>${g.region?`<span class="pill">${esc(g.region)}</span>`:''}${g.format?`<span class="pill">${esc(g.format)}</span>`:''}${(g.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="pill ${g.status==='Acquis'?'good':'wanted'}">${esc(g.status)}</span></div></div><div class="qty">${g.quantity>1?`×${g.quantity}`:'›'}</div></article>`}).join('');els.empty.classList.toggle('hidden',v.length>0||!has)}
function setConsoleOptions(manufacturer,current=''){const existing=games.filter(g=>!manufacturer||g.manufacturer===manufacturer).map(g=>g.console),catalog=CONSOLE_CATALOG[manufacturer]||Object.values(CONSOLE_CATALOG).flat(),consoles=uniq([...existing,...catalog,current]);$('#console').innerHTML=consoles.map(c=>`<option ${c===current?'selected':''}>${esc(c)}</option>`).join('')}
function openForm(g=null){$('#dialogTitle').textContent=g?'Modifier':'Ajouter';$('#gameId').value=g?.id||'';$('#title').value=g?.title||'';const makers=uniq(games.map(x=>x.manufacturer));$('#manufacturer').value=g?.manufacturer||makers[0]||'Sony';setConsoleOptions($('#manufacturer').value,g?.console||'');$('#status').value=g?.status||'Acquis';$('#quantity').value=g?.quantity||1;$('#region').value=g?.region||'';$('#format').value=g?.format||'';$('#tags').value=(g?.tags||[]).join(', ');$('#notes').value=g?.notes||'';$('#deleteBtn').classList.toggle('hidden',!g);els.dialog.showModal()}
function normalizeImported(data){const arr=Array.isArray(data)?data:(Array.isArray(data.games)?data.games:null);if(!arr)throw new Error('Format JSON non reconnu');return arr.filter(x=>x&&typeof x==='object'&&x.title).map((g,i)=>({id:String(g.id||`import-${Date.now()}-${i}`),title:String(g.title||'').trim(),manufacturer:String(g.manufacturer||'Autre'),console:String(g.console||'Autre'),status:g.status==='Recherché'?'Recherché':'Acquis',quantity:Math.max(1,Number(g.quantity)||1),region:String(g.region||''),format:String(g.format||''),tags:Array.isArray(g.tags)?g.tags.map(String):[],notes:String(g.notes||''),source:String(g.source||'import')}))}
async function importFile(file){try{const text=await file.text();const imported=normalizeImported(JSON.parse(text));const replace=!games.length||confirm(`Importer ${imported.length} jeux ?\n\nOK = remplacer la collection locale\nAnnuler = conserver la collection actuelle`);if(replace){games=imported}else{return}save();populateFilters();render();alert(`${imported.length} jeux importés sur cet appareil.\nAucune donnée n'a été envoyée à GitHub.`)}catch(err){alert(`Import impossible : ${err.message}`)}finally{els.file.value=''}}
els.search.addEventListener('input',render);els.sf.addEventListener('change',render);els.mf.addEventListener('change',()=>{populateFilters(els.mf.value,els.cf.value);render()});els.cf.addEventListener('change',()=>{const consoleName=els.cf.value,makers=uniq(games.filter(g=>g.console===consoleName).map(g=>g.manufacturer));if(consoleName&&makers.length===1&&els.mf.value!==makers[0])populateFilters(makers[0],consoleName);render()});
els.cards.addEventListener('click',e=>{const b=e.target.closest('[data-maker]');if(!b)return;const manufacturer=els.mf.value===b.dataset.maker?'':b.dataset.maker;populateFilters(manufacturer,'');render()});els.list.addEventListener('click',e=>{const c=e.target.closest('[data-id]');if(c)openForm(games.find(g=>g.id===c.dataset.id))});
$('#refreshBtn').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.classList.add('refreshing');button.setAttribute('aria-label','Actualisation en cours');try{if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.getRegistration();await registration?.update()}}catch{}finally{location.reload()}};
$('#addBtn').onclick=()=>openForm();$('#clearFilters').onclick=()=>{els.search.value='';els.sf.value='';populateFilters('','');render()};$('#manufacturer').onchange=e=>setConsoleOptions(e.target.value);
els.form.addEventListener('submit',e=>{e.preventDefault();const id=$('#gameId').value;const obj={id:id||'g'+Date.now(),title:$('#title').value.trim(),manufacturer:$('#manufacturer').value,console:$('#console').value,status:$('#status').value,quantity:Math.max(1,+$('#quantity').value||1),region:$('#region').value,format:$('#format').value,tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('#notes').value.trim(),source:id?(games.find(g=>g.id===id)?.source||'manuel'):'manuel'};if(id)games=games.map(g=>g.id===id?obj:g);else games.push(obj);save();populateFilters();els.dialog.close();render()});
$('#deleteBtn').onclick=()=>{const id=$('#gameId').value;if(id&&confirm('Supprimer ce jeu de RétroMax ?')){games=games.filter(g=>g.id!==id);save();populateFilters();els.dialog.close();render()}};
$('.bottom-nav').addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(!b)return;document.querySelectorAll('.nav-item[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');els.sf.value=b.dataset.nav==='wanted'?'Recherché':'';render()});
function chooseImport(){els.file.click()}$('#importBtn').onclick=chooseImport;$('#welcomeImportBtn').onclick=chooseImport;els.file.onchange=e=>{const f=e.target.files?.[0];if(f)importFile(f)};
$('#exportBtn').onclick=()=>{const payload={app:'RétroMax',version:2,exportedAt:new Date().toISOString(),games};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`retromax-sauvegarde-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
populateFilters();render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
