const KEY='retromax-games-v2-private';
const APP_VERSION='0.0.23';
const DEFAULT_ACCENT='#f7cf46';
const CONSOLE_CATALOG={
  Sony:['PlayStation 1','PlayStation 2','PlayStation 3','PlayStation 4','PlayStation 5','PSP','PS Vita'],
  Nintendo:['NES','Super Nintendo','Nintendo 64','GameCube','Wii','Wii U','Switch','Nintendo Switch 2','Game Boy','Game Boy Color','Game Boy Advance','Nintendo DS','Nintendo 3DS'],
  Sega:['Master System','Mega Drive','Saturn','Dreamcast','Game Gear'],
  Microsoft:['Xbox','Xbox 360','Xbox One','Xbox Series']
};
const PLATFORM_THEMES=[
  {key:'ps5',match:/playstation 5|\bps5\b/,color:'#f1f5ff',mark:'PS5',logo:'playstation5',shape:'wordmark',mode:'image'},
  {key:'ps4',match:/playstation 4|\bps4\b/,color:'#147bd1',mark:'PS4',logo:'playstation4',shape:'wordmark',mode:'image'},
  {key:'ps3',match:/playstation 3|\bps3\b/,color:'#aeb8c7',mark:'PS3',logo:'playstation3',shape:'wordmark',mode:'image'},
  {key:'ps2',match:/playstation 2|\bps2\b/,color:'#6574ff',mark:'PS2',logo:'playstation2',shape:'wordmark',mode:'image'},
  {key:'psvita',match:/ps vita|playstation vita/,color:'#20a9e0',mark:'VITA',logo:'psvita',shape:'handheld-wordmark',mode:'image'},
  {key:'psp',match:/\bpsp\b|playstation portable/,color:'#9aa5b8',mark:'PSP',logo:'psp',shape:'handheld-wordmark',mode:'image'},
  {key:'n64',match:/nintendo 64|\bn64\b/,color:'#069330',mark:'N64',logo:'nintendo64',mode:'image'},
  {key:'snes',match:/super nintendo|super nes|\bsnes\b|super famicom/,color:'#6eb92b',mark:'SNES',logo:'super-nintendo',mode:'image'},
  {key:'nes',match:/nintendo entertainment system|\bnes\b/,color:'#e60012',mark:'NES',logo:'nintendo-nes',shape:'heritage-wordmark',mode:'image'},
  {key:'gamecube',match:/gamecube/,color:'#7357d6',mark:'GC',logo:'gamecube'},
  {key:'switch2',match:/nintendo switch 2|switch 2/,color:'#e60012',mark:'NS2',logo:'nintendo-switch-2',shape:'legacy-wordmark',mode:'image'},
  {key:'switch',match:/switch/,color:'#e60012',mark:'NS',logo:'nintendo-switch'},
  {key:'wiiu',match:/wii u|wiiu/,color:'#00a7e0',mark:'WiiU',logo:'nintendo-wiiu',shape:'legacy-wordmark',mode:'image'},
  {key:'wii',match:/\bwii\b/,color:'#00a7e0',mark:'Wii',logo:'nintendo-wii'},
  {key:'gameboyadvance',match:/game boy advance|\bgba\b/,color:'#6545a5',mark:'GBA',logo:'game-boy-advance',shape:'heritage-wordmark',mode:'image'},
  {key:'gameboycolor',match:/game boy color|\bgbc\b/,color:'#9b4d96',mark:'GBC',logo:'game-boy-color',shape:'heritage-wordmark',mode:'image'},
  {key:'gameboy',match:/game boy/,color:'#2f328c',mark:'GB',logo:'game-boy',shape:'heritage-wordmark',mode:'image'},
  {key:'3ds',match:/nintendo 3ds|\b3ds\b/,color:'#e60012',mark:'3DS',logo:'nintendo-3ds',shape:'legacy-wordmark',mode:'image'},
  {key:'ds',match:/nintendo ds|\bds\b/,color:'#aeb8c7',mark:'DS',logo:'nintendo-ds',shape:'heritage-wordmark',mode:'image'},
  {key:'mastersystem',match:/master system/,color:'#e4312b',mark:'MS',logo:'master-system',shape:'legacy-wordmark',mode:'image'},
  {key:'megadrive',match:/mega drive|genesis/,color:'#ff5a2a',mark:'MD',logo:'mega-drive',shape:'legacy-wordmark',mode:'image'},
  {key:'saturn',match:/saturn/,color:'#5b7fb8',mark:'SAT',logo:'sega-saturn',mode:'image'},
  {key:'dreamcast',match:/dreamcast/,color:'#f36f21',mark:'DC',logo:'dreamcast'},
  {key:'xboxseries',match:/xbox series/,color:'#107c10',mark:'XS',logo:'xbox-series',shape:'legacy-wordmark',mode:'image'},
  {key:'xboxone',match:/xbox one/,color:'#107c10',mark:'X1',logo:'xbox-one',shape:'legacy-wordmark',mode:'image'},
  {key:'xbox360',match:/xbox 360/,color:'#6abf4b',mark:'360',logo:'xbox-360',shape:'legacy-wordmark',mode:'image'},
  {key:'xbox',match:/xbox/,color:'#52b043',mark:'XB',logo:'xbox-original',shape:'legacy-wordmark',mode:'image'},
  {key:'playstation',match:/playstation(?: 1)?|\bps1\b|sony/,color:'#1675d1',mark:'PS',logo:'playstation-classic',mode:'image'},
  {key:'nintendo',match:/nintendo|\bnes\b|game boy|\bwii\b|\b3ds\b|\bds\b/,color:'#e60012',mark:'N',logo:'nintendo-mark',mode:'image'},
  {key:'sega',match:/sega|master system|mega drive|saturn|game gear/,color:'#0089cf',mark:'SEGA',logo:'sega'},
  {key:'microsoft',match:/microsoft/,color:'#52b043',mark:'MS',logo:'xbox'}
];
let games=load();
let selectionMode=false;
const selectedGameIds=new Set();
const $=s=>document.querySelector(s);
const els={stats:$('#stats'),search:$('#search'),mf:$('#manufacturerFilter'),cf:$('#consoleFilter'),sf:$('#statusFilter'),cards:$('#manufacturerCards'),list:$('#gameList'),empty:$('#emptyState'),result:$('#resultTitle'),dialog:$('#gameDialog'),form:$('#gameForm'),welcome:$('#emptyWelcome'),privacy:$('#privacyBanner'),file:$('#importFile'),selectModeBtn:$('#selectModeBtn'),selectionBar:$('#selectionBar'),selectionCount:$('#selectionCount'),selectAllVisible:$('#selectAllVisible'),bulkEditBtn:$('#bulkEditBtn'),bulkDialog:$('#bulkDialog'),bulkForm:$('#bulkForm'),scanDialog:$('#scanDialog'),scanVideo:$('#scanVideo'),scanStatus:$('#scanStatus'),barcodeInput:$('#barcodeInput'),barcodeLookupBtn:$('#barcodeLookupBtn'),scanBlankBtn:$('#scanBlankBtn')};
$('#appVersion').textContent=`v${APP_VERSION}`;
function load(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):[]}catch{return []}}
function save(){localStorage.setItem(KEY,JSON.stringify(games))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uniq(xs){return [...new Set(xs.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'))}
function platformTheme(consoleName='',manufacturer=''){const haystack=`${consoleName} ${manufacturer}`.toLowerCase();return PLATFORM_THEMES.find(theme=>theme.match.test(haystack))||{key:'other',color:DEFAULT_ACCENT,mark:'•'}}
function platformStyle(theme){return `--platform-accent:${theme.color};--platform-soft:${theme.color}24${theme.logo?`;--platform-logo:url(assets/platforms/${theme.logo}.svg)`:''}`}
function platformMark(theme,label){const mode=theme.mode||'mask',shape=theme.shape||'emblem',image=theme.logo&&mode==='image'?`<img class="platform-logo-image" src="assets/platforms/${theme.logo}.svg?v=${APP_VERSION}" alt="" loading="lazy">`:'';return `<span class="platform-mark" data-platform-logo="${theme.key}" data-logo-mode="${mode}" data-logo-shape="${shape}" data-has-logo="${theme.logo?'true':'false'}" role="img" aria-label="${esc(label)}">${image}<span class="platform-fallback">${esc(theme.mark)}</span></span>`}
function applyActiveTheme(){const theme=els.cf.value?platformTheme(els.cf.value):els.mf.value?platformTheme('',els.mf.value):null;document.documentElement.style.setProperty('--accent',theme?.color||DEFAULT_ACCENT);document.documentElement.style.setProperty('--accent-soft',theme?`${theme.color}24`:'#f7cf4624');document.body.dataset.activePlatform=theme?.key||'all'}
function populateFilters(manufacturer=els.mf.value,consoleName=els.cf.value){const m=uniq(games.map(g=>g.manufacturer));els.mf.innerHTML='<option value="">Tous les constructeurs</option>'+m.map(x=>`<option>${esc(x)}</option>`).join('');els.mf.value=m.includes(manufacturer)?manufacturer:'';const c=uniq(games.filter(g=>!els.mf.value||g.manufacturer===els.mf.value).map(g=>g.console));els.cf.innerHTML='<option value="">Toutes les consoles</option>'+c.map(x=>`<option>${esc(x)}</option>`).join('');els.cf.value=c.includes(consoleName)?consoleName:'';const fm=$('#manufacturer'),fc=$('#console'),formMakers=uniq([...Object.keys(CONSOLE_CATALOG),...m]),allConsoles=uniq(games.map(g=>g.console));fm.innerHTML=formMakers.map(x=>`<option>${esc(x)}</option>`).join('');fc.innerHTML=allConsoles.length?allConsoles.map(x=>`<option>${esc(x)}</option>`).join(''):'<option>PlayStation 1</option>'}
function visible(){const q=els.search.value.trim().toLowerCase(),mf=els.mf.value,cf=els.cf.value,sf=els.sf.value;return games.filter(g=>(!q||[g.title,g.console,g.manufacturer,g.region,g.format,...(g.tags||[])].join(' ').toLowerCase().includes(q))&&(!mf||g.manufacturer===mf)&&(!cf||g.console===cf)&&(!sf||g.status===sf)).sort((a,b)=>(a.console||'').localeCompare(b.console||'','fr')||(a.title||'').localeCompare(b.title||'','fr'))}
function render(){applyActiveTheme();const has=games.length>0;els.welcome.classList.toggle('hidden',has);els.privacy.classList.toggle('hidden',!has);const owned=games.filter(g=>g.status==='Acquis'),wanted=games.filter(g=>g.status==='Recherché');els.stats.innerHTML=`<div class="stat"><strong>${owned.reduce((n,g)=>n+(g.quantity||1),0)}</strong><span>exemplaires acquis</span></div><div class="stat"><strong>${uniq(games.map(g=>g.console)).length}</strong><span>consoles</span></div><div class="stat"><strong>${wanted.length}</strong><span>recherchés</span></div>`;const makers=uniq(games.map(g=>g.manufacturer));els.cards.innerHTML=makers.map(m=>{const n=games.filter(g=>g.manufacturer===m&&g.status==='Acquis').reduce((s,g)=>s+(g.quantity||1),0),theme=platformTheme('',m);return `<button class="maker-card ${els.mf.value===m?'active':''}" data-maker="${esc(m)}" data-platform="${theme.key}" style="${platformStyle(theme)}">${platformMark(theme,m)}<span class="maker-copy"><strong>${esc(m)}</strong><span>${n} exemplaires · ${uniq(games.filter(g=>g.manufacturer===m).map(g=>g.console)).length} consoles</span></span></button>`}).join('');const v=visible();const label=[els.mf.value,els.cf.value,els.sf.value].filter(Boolean).join(' · ')||'Toute la collection';els.result.textContent=`${label} (${v.length})`;els.list.innerHTML=v.map(g=>{const theme=platformTheme(g.console,g.manufacturer),selected=selectedGameIds.has(g.id),end=selectionMode?`<span class="selection-check" aria-hidden="true">${selected?'✓':''}</span>`:`<div class="qty">${g.quantity>1?`×${g.quantity}`:'›'}</div>`;return `<article class="game-card ${selectionMode?'selectable':''} ${selected?'selected':''}" data-id="${esc(g.id)}" data-platform="${theme.key}" style="${platformStyle(theme)}" ${selectionMode?`role="checkbox" tabindex="0" aria-checked="${selected}"`:''}>${platformMark(theme,g.console)}<div class="game-copy"><h3>${esc(g.title)}</h3><div class="meta"><span class="pill console-pill">${esc(g.console)}</span>${g.region?`<span class="pill">${esc(g.region)}</span>`:''}${g.format?`<span class="pill">${esc(g.format)}</span>`:''}${(g.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="pill ${g.status==='Acquis'?'good':'wanted'}">${esc(g.status)}</span></div></div>${end}</article>`}).join('');els.empty.classList.toggle('hidden',v.length>0||!has);const count=selectedGameIds.size,allVisible=v.length>0&&v.every(g=>selectedGameIds.has(g.id));els.selectModeBtn.setAttribute('aria-pressed',String(selectionMode));els.selectModeBtn.setAttribute('aria-label',selectionMode?'Quitter la sélection multiple':'Sélectionner plusieurs jeux');els.selectionBar.classList.toggle('hidden',!selectionMode);els.selectionCount.textContent=`${count} jeu${count>1?'x':''} sélectionné${count>1?'s':''}`;els.selectAllVisible.textContent=allVisible?'Tout désélectionner':`Tout sélectionner${v.length?` (${v.length})`:''}`;els.selectAllVisible.disabled=!v.length;els.bulkEditBtn.disabled=!count}
function setSelectionMode(active){selectionMode=active;if(!active)selectedGameIds.clear();render()}
function toggleVisibleSelection(){const v=visible(),allSelected=v.length&&v.every(g=>selectedGameIds.has(g.id));v.forEach(g=>allSelected?selectedGameIds.delete(g.id):selectedGameIds.add(g.id));render()}
function openBulkForm(){if(!selectedGameIds.size)return;els.bulkForm.reset();['Region','Format','Status','Tags'].forEach(name=>{$(`#bulk${name}`).disabled=true;if(name==='Tags')$('#bulkTagsMode').disabled=true});$('#bulkError').classList.add('hidden');$('#bulkDialogCount').textContent=selectedGameIds.size;els.bulkDialog.showModal()}
function setConsoleOptions(manufacturer,current=''){const existing=games.filter(g=>!manufacturer||g.manufacturer===manufacturer).map(g=>g.console),catalog=CONSOLE_CATALOG[manufacturer]||Object.values(CONSOLE_CATALOG).flat(),consoles=uniq([...existing,...catalog,current]);$('#console').innerHTML=consoles.map(c=>`<option ${c===current?'selected':''}>${esc(c)}</option>`).join('')}
function openForm(g=null,preset=null){if(els.dialog.open)return false;const data=g||preset||{};$('#dialogTitle').textContent=g?'Modifier':preset?'Vérifier le préremplissage':'Ajouter';$('#gameId').value=g?.id||'';$('#entrySource').value=g?.source||(preset?.scanned?'scan':'manuel');$('#title').value=data.title||'';const makers=uniq([...Object.keys(CONSOLE_CATALOG),...games.map(x=>x.manufacturer)]),manufacturer=data.manufacturer||makers[0]||'Sony';$('#manufacturer').value=manufacturer;setConsoleOptions(manufacturer,data.console||'');$('#status').value=data.status||'Acquis';$('#quantity').value=data.quantity||1;$('#region').value=data.region||'';$('#format').value=data.format||'';$('#tags').value=(data.tags||[]).join(', ');$('#notes').value=data.notes||'';const note=$('#scanPrefillNote');note.textContent=preset?.barcode?`Code-barres ${preset.barcode} détecté. Vérifie et corrige les informations proposées avant d’enregistrer.`:'';note.classList.toggle('hidden',!preset?.scanned);$('#deleteBtn').classList.toggle('hidden',!g);els.dialog.showModal();return true}

const PLATFORM_GUESSES=[
  {match:/\b(?:ps5|playstation\s*5)\b/i,manufacturer:'Sony',console:'PlayStation 5'},
  {match:/\b(?:ps4|playstation\s*4)\b/i,manufacturer:'Sony',console:'PlayStation 4'},
  {match:/\b(?:ps3|playstation\s*3)\b/i,manufacturer:'Sony',console:'PlayStation 3'},
  {match:/\b(?:ps2|playstation\s*2)\b/i,manufacturer:'Sony',console:'PlayStation 2'},
  {match:/\b(?:ps\s*vita|playstation\s*vita)\b/i,manufacturer:'Sony',console:'PS Vita'},
  {match:/\b(?:psp|playstation\s*portable)\b/i,manufacturer:'Sony',console:'PSP'},
  {match:/\b(?:ps1|playstation(?:\s*1)?)\b/i,manufacturer:'Sony',console:'PlayStation 1'},
  {match:/\b(?:nintendo\s*)?switch\s*2\b/i,manufacturer:'Nintendo',console:'Nintendo Switch 2'},
  {match:/\b(?:nintendo\s*)?switch\b/i,manufacturer:'Nintendo',console:'Switch'},
  {match:/\bwii\s*u\b/i,manufacturer:'Nintendo',console:'Wii U'},
  {match:/\bwii\b/i,manufacturer:'Nintendo',console:'Wii'},
  {match:/\b(?:nintendo\s*)?3ds\b/i,manufacturer:'Nintendo',console:'Nintendo 3DS'},
  {match:/\b(?:nintendo\s*)?ds\b/i,manufacturer:'Nintendo',console:'Nintendo DS'},
  {match:/\b(?:game\s*boy\s*advance|gba)\b/i,manufacturer:'Nintendo',console:'Game Boy Advance'},
  {match:/\b(?:game\s*boy\s*color|gbc)\b/i,manufacturer:'Nintendo',console:'Game Boy Color'},
  {match:/\bgame\s*boy\b/i,manufacturer:'Nintendo',console:'Game Boy'},
  {match:/\b(?:nintendo\s*64|n64)\b/i,manufacturer:'Nintendo',console:'Nintendo 64'},
  {match:/\b(?:super\s*nintendo|super\s*nes|snes|super\s*famicom)\b/i,manufacturer:'Nintendo',console:'Super Nintendo'},
  {match:/\b(?:nintendo\s*entertainment\s*system|nes)\b/i,manufacturer:'Nintendo',console:'NES'},
  {match:/\bgamecube\b/i,manufacturer:'Nintendo',console:'GameCube'},
  {match:/\bxbox\s*series(?:\s*[xs])?\b/i,manufacturer:'Microsoft',console:'Xbox Series'},
  {match:/\bxbox\s*one\b/i,manufacturer:'Microsoft',console:'Xbox One'},
  {match:/\bxbox\s*360\b/i,manufacturer:'Microsoft',console:'Xbox 360'},
  {match:/\bxbox\b/i,manufacturer:'Microsoft',console:'Xbox'},
  {match:/\bdreamcast\b/i,manufacturer:'Sega',console:'Dreamcast'},
  {match:/\b(?:sega\s*)?saturn\b/i,manufacturer:'Sega',console:'Saturn'},
  {match:/\b(?:mega\s*drive|genesis)\b/i,manufacturer:'Sega',console:'Mega Drive'},
  {match:/\bmaster\s*system\b/i,manufacturer:'Sega',console:'Master System'},
  {match:/\bgame\s*gear\b/i,manufacturer:'Sega',console:'Game Gear'}
];
let scanReader=null,scanStream=null,scanLookupController=null,scanRun=0,scanPhase='idle',pendingBarcode='';
function setScanPhase(phase){scanPhase=phase;els.scanDialog.dataset.state=phase;els.scanDialog.setAttribute('aria-busy',phase==='lookup'?'true':'false')}
function setScanStatus(message,state=''){els.scanStatus.textContent=message;els.scanStatus.dataset.state=state}
function stopScanner(){const reader=scanReader,stream=scanStream||els.scanVideo.srcObject;scanReader=null;scanStream=null;try{reader?.reset?.()}catch{}try{els.scanVideo.pause()}catch{}if(stream)stream.getTracks().forEach(track=>track.stop());els.scanVideo.srcObject=null}
function abortScanLookup(){const controller=scanLookupController;scanLookupController=null;controller?.abort()}
function afterDialogPaint(){return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))}
async function closeDialogSafely(dialog,returnValue=''){if(!dialog.open)return;await new Promise(resolve=>{let finished=false,timer;const done=()=>{if(finished)return;finished=true;clearTimeout(timer);dialog.removeEventListener('close',done);resolve()};dialog.addEventListener('close',done,{once:true});try{dialog.close(returnValue)}catch{dialog.removeAttribute('open');done()}if(!finished)timer=setTimeout(()=>{if(dialog.open)dialog.removeAttribute('open');done()},250)});await afterDialogPaint()}
function closeGameForm(){return closeDialogSafely(els.dialog,'cancel')}
async function cancelScanner(){scanRun+=1;abortScanLookup();stopScanner();setScanPhase('idle');els.barcodeLookupBtn.disabled=false;if(els.scanDialog.open)await closeDialogSafely(els.scanDialog,'cancel')}
async function openScannedForm(preset,run=scanRun){if(run!==scanRun||!['lookup','manual'].includes(scanPhase))return;setScanPhase('handoff');scanLookupController=null;stopScanner();await closeDialogSafely(els.scanDialog);if(run!==scanRun||scanPhase!=='handoff')return;openForm(null,preset);setScanPhase('complete')}
function inferPlatform(text=''){return PLATFORM_GUESSES.find(item=>item.match.test(text))||null}
function inferRegion(text=''){if(/\b(?:japan|japanese|ntsc[\s-]*j|jap)\b/i.test(text))return'JAP';if(/\b(?:usa?|north america|ntsc[\s-]*u)\b/i.test(text))return'US';if(/\b(?:germany|german|deutsch|\bde\b)\b/i.test(text))return'DE';if(/\b(?:europe|european|pal)\b/i.test(text))return'PAL';return''}
function scannedPreset(item,barcode){const haystack=[item?.name,item?.platform].filter(Boolean).join(' '),platform=inferPlatform(haystack),regionCode=String(item?.regionInfo||'').toLowerCase(),region=regionCode==='jp'?'JAP':regionCode==='us'||regionCode==='ca'?'US':regionCode==='de'?'DE':regionCode?'PAL':inferRegion(haystack);return{title:String(item?.name||'').trim(),manufacturer:platform?.manufacturer||'Sony',console:platform?.console||'PlayStation 1',status:'Acquis',quantity:1,region,format:'Boîte',tags:[],notes:`Code-barres : ${barcode}${item?'\nPrérempli via LevelComplete.':''}`,barcode,scanned:true}}
async function fetchBarcodeItem(barcode,signal){const target=`https://levelcomplete.de/api/public/search.php?${barcode}`,sources=[target,`https://corsproxy.io/?url=${encodeURIComponent(target)}`];let lastError=new Error('network');for(const url of sources){try{const response=await fetch(url,{headers:{Accept:'application/json'},signal});if(response.status===429)throw new Error('limit');if(!response.ok){lastError=new Error('network');continue}const payload=await response.json();return Array.isArray(payload)?payload[0]||null:null}catch(error){if(signal.aborted||error.name==='AbortError'||error.message==='limit')throw error;lastError=error}}throw lastError}
async function lookupBarcode(raw,run=scanRun){if(run!==scanRun||!['camera','manual'].includes(scanPhase))return;const barcode=String(raw||'').replace(/\D/g,'');if(!/^\d{8,14}$/.test(barcode)){setScanStatus('Entre un code-barres composé de 8 à 14 chiffres.','error');return}pendingBarcode=barcode;els.barcodeInput.value=barcode;els.scanBlankBtn.classList.add('hidden');els.barcodeLookupBtn.disabled=true;setScanPhase('lookup');stopScanner();setScanStatus('Code détecté. Recherche du jeu…','success');const controller=new AbortController();let timedOut=false;const timeout=setTimeout(()=>{timedOut=true;controller.abort()},10000);scanLookupController=controller;try{const item=await fetchBarcodeItem(barcode,controller.signal);if(run!==scanRun||controller.signal.aborted||scanPhase!=='lookup')return;if(!item)throw new Error('not-found');await openScannedForm(scannedPreset(item,barcode),run)}catch(error){if(run!==scanRun||(error.name==='AbortError'&&!timedOut))return;const message=error.message==='limit'?'La limite du service de recherche est atteinte. Tu peux tout de même créer la fiche.':error.message==='not-found'?'Aucun jeu trouvé pour ce code. Tu peux créer la fiche et la compléter.':'Recherche impossible pour le moment. Tu peux créer la fiche manuellement.';setScanPhase('manual');setScanStatus(message,'error');els.scanBlankBtn.classList.remove('hidden')}finally{clearTimeout(timeout);if(run===scanRun&&scanLookupController===controller)scanLookupController=null;if(run===scanRun)els.barcodeLookupBtn.disabled=false}}
async function startScanner(){if(selectionMode)setSelectionMode(false);scanRun+=1;const run=scanRun;abortScanLookup();stopScanner();pendingBarcode='';els.barcodeInput.value='';els.barcodeLookupBtn.disabled=false;els.scanBlankBtn.classList.add('hidden');setScanStatus('Autorise la caméra, puis place le code-barres dans le cadre.');setScanPhase('camera');if(!els.scanDialog.open)els.scanDialog.showModal();if(!navigator.mediaDevices?.getUserMedia){setScanPhase('manual');setScanStatus('La caméra n’est pas disponible ici. Saisis le code-barres ci-dessous.','error');return}if(!window.ZXing?.BrowserMultiFormatReader){setScanPhase('manual');setScanStatus('Le lecteur de code-barres n’a pas pu être chargé. Saisis le numéro ci-dessous.','error');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(run!==scanRun||scanPhase!=='camera'||!els.scanDialog.open){stream.getTracks().forEach(track=>track.stop());return}scanStream=stream;const hints=new Map();hints.set(ZXing.DecodeHintType.POSSIBLE_FORMATS,[ZXing.BarcodeFormat.EAN_13,ZXing.BarcodeFormat.EAN_8,ZXing.BarcodeFormat.UPC_A,ZXing.BarcodeFormat.UPC_E]);const reader=new ZXing.BrowserMultiFormatReader(hints,350);reader.timeBetweenDecodingAttempts=180;scanReader=reader;await reader.decodeFromStream(stream,els.scanVideo,(result)=>{if(result&&run===scanRun&&scanPhase==='camera')lookupBarcode(result.getText(),run)});if(run!==scanRun||scanPhase!=='camera'||!els.scanDialog.open){try{reader.reset?.()}catch{}stream.getTracks().forEach(track=>track.stop())}}catch(error){if(run!==scanRun||scanPhase!=='camera')return;stopScanner();const denied=error?.name==='NotAllowedError'||error?.name==='PermissionDeniedError';setScanPhase('manual');setScanStatus(denied?'Accès à la caméra refusé. Autorise-la dans les réglages de l’iPhone, ou saisis le code-barres.':'Impossible d’ouvrir la caméra. Saisis le code-barres ci-dessous.','error')}}
function normalizeImported(data){const arr=Array.isArray(data)?data:(Array.isArray(data.games)?data.games:null);if(!arr)throw new Error('Format JSON non reconnu');return arr.filter(x=>x&&typeof x==='object'&&x.title).map((g,i)=>({id:String(g.id||`import-${Date.now()}-${i}`),title:String(g.title||'').trim(),manufacturer:String(g.manufacturer||'Autre'),console:String(g.console||'Autre'),status:g.status==='Recherché'?'Recherché':'Acquis',quantity:Math.max(1,Number(g.quantity)||1),region:String(g.region||''),format:String(g.format||''),tags:Array.isArray(g.tags)?g.tags.map(String):[],notes:String(g.notes||''),source:String(g.source||'import')}))}
async function importFile(file){try{const text=await file.text();const imported=normalizeImported(JSON.parse(text));const replace=!games.length||confirm(`Importer ${imported.length} jeux ?\n\nOK = remplacer la collection locale\nAnnuler = conserver la collection actuelle`);if(replace){games=imported}else{return}save();populateFilters();render();alert(`${imported.length} jeux importés sur cet appareil.\nAucune donnée n'a été envoyée à GitHub.`)}catch(err){alert(`Import impossible : ${err.message}`)}finally{els.file.value=''}}
els.search.addEventListener('input',render);els.sf.addEventListener('change',render);els.mf.addEventListener('change',()=>{populateFilters(els.mf.value,els.cf.value);render()});els.cf.addEventListener('change',()=>{const consoleName=els.cf.value,makers=uniq(games.filter(g=>g.console===consoleName).map(g=>g.manufacturer));if(consoleName&&makers.length===1&&els.mf.value!==makers[0])populateFilters(makers[0],consoleName);render()});
els.cards.addEventListener('click',e=>{const b=e.target.closest('[data-maker]');if(!b)return;const manufacturer=els.mf.value===b.dataset.maker?'':b.dataset.maker;populateFilters(manufacturer,'');render()});els.list.addEventListener('click',e=>{const c=e.target.closest('[data-id]');if(!c)return;if(selectionMode){selectedGameIds.has(c.dataset.id)?selectedGameIds.delete(c.dataset.id):selectedGameIds.add(c.dataset.id);render();return}openForm(games.find(g=>g.id===c.dataset.id))});
els.list.addEventListener('keydown',e=>{if(!selectionMode||!['Enter',' '].includes(e.key))return;const c=e.target.closest('[data-id]');if(c){e.preventDefault();c.click()}});
$('#refreshBtn').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.classList.add('refreshing');button.setAttribute('aria-label','Actualisation en cours');try{if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.getRegistration();await registration?.update()}}catch{}finally{location.reload()}};
$('#scanBtn').onclick=startScanner;$('#scanCloseBtn').onclick=cancelScanner;els.scanDialog.addEventListener('cancel',event=>{event.preventDefault();cancelScanner()});els.scanDialog.addEventListener('close',()=>{stopScanner();if(!['handoff','idle'].includes(scanPhase)){scanRun+=1;abortScanLookup();setScanPhase('idle')}});$('#barcodeLookupBtn').onclick=()=>lookupBarcode(els.barcodeInput.value);els.barcodeInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();lookupBarcode(e.currentTarget.value)}});els.scanBlankBtn.onclick=()=>{const barcode=els.barcodeInput.value.replace(/\D/g,'')||pendingBarcode;openScannedForm(scannedPreset(null,barcode),scanRun)};[$('#gameCloseBtn'),$('#gameCancelBtn')].forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();closeGameForm()}));els.dialog.addEventListener('cancel',event=>{event.preventDefault();closeGameForm()});const suspendScanner=()=>{if(els.scanDialog.open)cancelScanner()};document.addEventListener('visibilitychange',()=>{if(document.hidden)suspendScanner()});window.addEventListener('pagehide',suspendScanner);
$('#addBtn').onclick=()=>openForm();$('#clearFilters').onclick=()=>{els.search.value='';els.sf.value='';populateFilters('','');render()};els.selectModeBtn.onclick=()=>setSelectionMode(!selectionMode);els.selectAllVisible.onclick=toggleVisibleSelection;els.bulkEditBtn.onclick=openBulkForm;$('#cancelSelection').onclick=()=>setSelectionMode(false);$('#bulkCloseBtn').onclick=$('#bulkCancelBtn').onclick=()=>els.bulkDialog.close();$('#manufacturer').onchange=e=>setConsoleOptions(e.target.value);
['Region','Format','Status','Tags'].forEach(name=>{$(`#applyBulk${name}`).addEventListener('change',e=>{const enabled=e.target.checked;$(`#bulk${name}`).disabled=!enabled;if(name==='Tags')$('#bulkTagsMode').disabled=!enabled;$('#bulkError').classList.add('hidden')})});
els.bulkForm.addEventListener('submit',e=>{e.preventDefault();const applyRegion=$('#applyBulkRegion').checked,applyFormat=$('#applyBulkFormat').checked,applyStatus=$('#applyBulkStatus').checked,applyTags=$('#applyBulkTags').checked;if(![applyRegion,applyFormat,applyStatus,applyTags].some(Boolean)){$('#bulkError').classList.remove('hidden');return}const tags=$('#bulkTags').value.split(',').map(x=>x.trim()).filter(Boolean),tagsMode=$('#bulkTagsMode').value;games=games.map(g=>{if(!selectedGameIds.has(g.id))return g;const updated={...g};if(applyRegion)updated.region=$('#bulkRegion').value;if(applyFormat)updated.format=$('#bulkFormat').value;if(applyStatus)updated.status=$('#bulkStatus').value;if(applyTags)updated.tags=tagsMode==='replace'?tags:uniq([...(g.tags||[]),...tags]);return updated});save();const manufacturer=els.mf.value,consoleName=els.cf.value;populateFilters(manufacturer,consoleName);els.bulkDialog.close();setSelectionMode(false)});
els.form.addEventListener('submit',e=>{e.preventDefault();const id=$('#gameId').value;const obj={id:id||'g'+Date.now(),title:$('#title').value.trim(),manufacturer:$('#manufacturer').value,console:$('#console').value,status:$('#status').value,quantity:Math.max(1,+$('#quantity').value||1),region:$('#region').value,format:$('#format').value,tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('#notes').value.trim(),source:id?(games.find(g=>g.id===id)?.source||'manuel'):($('#entrySource').value||'manuel')};if(id)games=games.map(g=>g.id===id?obj:g);else games.push(obj);save();populateFilters();els.dialog.close();render()});
$('#deleteBtn').onclick=()=>{const id=$('#gameId').value;if(id&&confirm('Supprimer ce jeu de RétroMax ?')){games=games.filter(g=>g.id!==id);selectedGameIds.delete(id);save();populateFilters();els.dialog.close();render()}};
$('.bottom-nav').addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(!b)return;document.querySelectorAll('.nav-item[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');els.sf.value=b.dataset.nav==='wanted'?'Recherché':'';render()});
function chooseImport(){els.file.click()}$('#importBtn').onclick=chooseImport;$('#welcomeImportBtn').onclick=chooseImport;els.file.onchange=e=>{const f=e.target.files?.[0];if(f)importFile(f)};
$('#exportBtn').onclick=()=>{const payload={app:'RétroMax',version:2,exportedAt:new Date().toISOString(),games};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`retromax-sauvegarde-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
populateFilters();render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
